# Generated by Django 3.1.7 on 2021-03-21 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50)),
                ('is_deck', models.BooleanField(default=False)),
                ('is_judge', models.BooleanField(default=False)),
                ('hand_size', models.IntegerField(default=7)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PromptCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_text', models.CharField(max_length=1000)),
                ('num_blanks', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=False)),
                ('won_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='game.player')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.session'),
        ),
        migrations.CreateModel(
            name='NounCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_text', models.CharField(max_length=1000)),
                ('in_hand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='game.player')),
                ('with_prompt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='game.promptcard')),
            ],
        ),
        migrations.CreateModel(
            name='AllCards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_text', models.CharField(max_length=1000)),
                ('is_noun', models.BooleanField(default=True)),
                ('num_blanks', models.IntegerField(default=0)),
                ('deck', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='game.deck')),
            ],
        ),
    ]
