# Generated by Django 3.1.7 on 2021-03-21 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allcards',
            name='num_blanks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nouncard',
            name='in_hand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.player'),
        ),
        migrations.AlterField(
            model_name='nouncard',
            name='with_prompt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.promptcard'),
        ),
        migrations.AlterField(
            model_name='promptcard',
            name='won_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.player'),
        ),
    ]
