# Generated by Django 3.1.7 on 2021-03-21 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20210321_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='has_played',
            field=models.BooleanField(default=False),
        ),
    ]
