# Generated by Django 3.1.7 on 2021-03-22 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_player_has_played'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allcards',
            name='num_blanks',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
