# Generated by Django 3.1.7 on 2021-03-26 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('game', '0004_auto_20210322_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='cookie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sessions.session'),
        ),
    ]
