# Generated by Django 3.1.7 on 2021-03-28 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_player_cookie'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='game_stage',
            field=models.IntegerField(default=0),
        ),
    ]
